name: Build, Test and Publish barfile
run-name: ${{ github.actor }} triggered build
on: [push]
jobs:
  build-and-publish-barfile:
    # Default token permissions
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    container: 
      # ACE versions: https://www.ibm.com/docs/en/app-connect/containers_cd?topic=obtaining-app-connect-enterprise-server-image-from-cloud-container-registry
      image: cp.icr.io/cp/appc/ace-server-prod@sha256:c1fac1a80768e26f64d8fff770b10a96b99b2bd4df2e2cd533e96f1a85ebec5c
      options: --user root
      credentials:
        username: cp
        password: ${{ secrets.entitlement_key }}
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: install-git-in-ace-container
        run: microdnf update && microdnf install --nodocs git 
      - uses: actions/checkout@v4
      - name: setup-gradle-in-ace-container
        uses: gradle/gradle-build-action@v2
        env:
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/mqm/bin:/opt/ibm/ace-12/common/jdk/bin
      - name: gradlew-build-and-publish-barfile
        run: | 
          source /opt/ibm/ace-12/server/bin/mqsiprofile
          export JAVA_HOME=/opt/ibm/ace-12/common/jdk 
          ./gradlew --no-daemon
          cp build/ace-hello-world.bar .
          git config --global --add safe.directory /__w/ace-hello-world/ace-hello-world
          git status
      - name: commit-bar-file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Committed bar file after publishing
          file_pattern: '*.bar'
