name: Build, Test and Publish barfile
run-name: ${{ github.actor }} triggered build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cp.icr.io/cp/appc/ace-server-prod:12.0.8.0-r2-20230524-022316@sha256:68c8723c97d2b70985972f25cf06f6b9d5a3e008c22e7df6f044c1dd988cb77f
      options: --user root
      credentials:
        username: cp
        password: ${{ secrets.entitlement_key }}
      volumes:
        - /home/runner/work/ace-hello-world/ace-hello-world:/home/aceuser/source
        - /var/lib/docker:/home/aceuser/docker
      env:
        USERNAME: ${{ secrets.package_publishing_username }}
        TOKEN: ${{ secrets.package_publishing_token }}
        GITHUB_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: run-gradlew
        run: source /opt/ibm/ace-12/server/bin/mqsiprofile; export JAVA_HOME=/opt/ibm/ace-12/common/jdk; /home/aceuser/source/gradlew --no-daemon
